# Generated by Django 5.0.7 on 2024-07-12 11:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('account_type', models.CharField(max_length=500)),
                ('balance', models.DecimalField(decimal_places=2, max_digits=100)),
                ('account_currency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cartegory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('cartegory_type', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=500)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transaction_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('date', models.DateField()),
                ('recurring', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.account')),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.cartegory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('transcation_type', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=1000)),
                ('start_date', models.DateField()),
                ('frequency', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.account')),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.cartegory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user')),
            ],
        ),
        migrations.CreateModel(
            name='Goal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('current_ammount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='cartegory',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user'),
        ),
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=100)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cartegory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.cartegory')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='FinanceTrackerAPI.user'),
        ),
    ]
